on: [ workflow_dispatch ]
jobs:
  create-artifacts:
    runs-on: act
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: extract version from manifest
        id: version
        run: cat system.json | echo version=`jq -r ".version"` >> "$FORGEJO_OUTPUT"

      - name: assert that the tag doesn't exist
        run: node scripts/tagExists.mjs
        env:
          TAG_NAME: ${{steps.version.output.version}}

      - name: build compendia
        run: node scripts/buildCompendia.mjs

      - name: compress files
        run: zip -r release.zip langs module styles templates README.md assets

      - name: upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          path: |
            system.json
            release.zip
          retention-days: 7
          if-no-files-found: error


  forgejo-release:
    runs-on: docker
    needs:
      - create-artifacts
    if: var.RELEASE_TO_FORGEJO
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: update manifest

      - name: create draft release


  github-release:
    runs-on: docker
    needs:
      - create-artifacts
    if: var.RELEASE_TO_GITHUB
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: update manifest

      - name: create draft release
